### ISSUE TITLE
Take advantage of `ht_feature_cached_string_add_mapping` for tracepoints

### ISSUE THREAD

**Issue by loganek** [AlexEne/rust_hawktracer#20]
This could be related to #8 
HawkTracer has a few helper methods attached to global timeline (which is AFAIK used in rust bindings by default) that allow to reduce amount of data being generated if the label of the tracepoint is stataic string - instead of copying the whole string to a listener, hawktracer can generate a mapping event (string address + string), and then use only the number when generating tracepoints.
HawkTracer C library [already implements the approach](https://github.com/amzn/hawktracer/blob/master/lib/include/hawktracer/string_scoped_tracepoint.h#L18) but since this is a macro, it must be re-implemented in Rust.
Based on my  quick research, that shouldn't be a problem, as Rust already supports [static threadlocal variables](https://doc.rust-lang.org/std/macro.thread_local.html)

**Comment by AlexEne** [comment]
Feature is in master so if anyone wants to test it out they can use:
```toml
[dependencies.rust_hawktracer]
git = "https://github.com/AlexEne/rust_hawktracer.git"
features=["profiling_enabled"]
```
